### ISSUE TITLE
The error "Name" ProjectTaskViewModel "does not exist in the namespace" clr-namespace: GanttControlDemoApp "."

### ISSUE THREAD

**Issue by it19862** [DevExpress-Examples/wpf-ganttcontrol-getting-started#1]
How to fix the error?

![2020-01-28_10-47-17](https://user-images.githubusercontent.com/18245828/73244731-b0da2e80-41bb-11ea-92c7-8ba912d1e2c2.png)

**Comment by Proxaaa** [comment]
Hello,

This issue can occur if you did not rebuild the project. If this does not help, please create a ticket in our [Support Center](https://www.devexpress.com/Support/Center/) so that our technical support engineers can provide more accurate assistance.
